name: fptp
networks:
  fptp-networks:
    driver: bridge
    enable_ipv4: true

volumes:
  fptp-persist-volumes:
    driver_opts:
      type: none
      o: bind
      device: /home/udhayarajanj/Development/Docker/Volumes/fptp

services:
  fptp_mysql_server:
    image: mysql:8.0.36
    container_name: fptp_mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fptp12345
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak123
    ports:
      - 4000:3306
    networks:
      - fptp-networks
    volumes:
      - fptp-persist-volumes:/var/lib/mysql
      - ./fptp-database/docker-restore-location:/docker-entrypoint-initdb.d

  fptp_keycloack_server:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: fptp_keycloack_server
    command: ["start-dev"]
    restart: always
    depends_on:
      - fptp_mysql_server
    networks:
      - fptp-networks
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: fptp_mysql_server
      KC_DB_URL_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin123
    ports:
      - 4001:8080
    
    